version: 2

updates:
  - package-ecosystem: terraform
    directory: /examples
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(docs)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
