formatter: markdown table

recursive:
  enabled: false

content: |-
  ## Usage

  ```hcl
  {{ include "examples/main.tf" }}

  # variables.tf

  {{ include "examples/variables.tf" }}

  # providers.tf

  {{ include "examples/providers.tf" }}
  ```

  ```hcl
  # terraform.tfvars

  {{ include "examples/terraform.tfvars.example" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject

settings:
  lockfile: false
