formatter: markdown table

recursive:
  enabled: false

content: |-
  ## Usage

  ### main.tf
  ```hcl
  {{ include "examples/main.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/variables.tf" }}
  ```

  ### providers.tf
  ```hcl
  {{ include "examples/providers.tf" }}
  ```

  ### terraform.tfvars
  ```hcl
  {{ include "examples/terraform.tfvars.example" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject

settings:
  lockfile: false
