name: Dependabot Automation

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  verify-checks:
    name: Verify Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Verify Checks
        run: |
          # Wait for incomplete checks to finish running.
          gh pr checks --required --watch
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  terraform-docs:
    name: Update Documentation
    runs-on: ubuntu-24.04
    needs: verify-checks
    if: needs.verify-checks.result == 'failure'
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Docs
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          git-push: true
          git-commit-message: 'docs: Update README.md'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
# if: github.event.pull_request.user.login == 'dependabot[bot]'
# if: github.event.pull_request.user.login == 'dependabot[bot]'
#  manage-pull-request:
#    name: Manage Pull Request
#    needs: verify-checks
#    runs-on: ubuntu-24.04
#    # if: github.event.pull_request.user.login == 'dependabot[bot]'
#    steps:
#      - name: Enable auto-merge
#        run: gh pr merge --auto --squash "${PR_URL}"
#        env:
#          PR_URL: ${{ github.event.pull_request.html_url }}
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
