name: Dependabot Automation

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    name: Update Documentation
    runs-on: ubuntu-22.04
    # if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Docs
        uses: terraform-docs/gh-actions@aeae0038ed47a547e0c0fca5c059d3335f48fb25 # v1.3.0
        with:
          git-push: true
          git-commit-message: 'docs: Update README.md'
  manage-pull-request:
    name: Manage Pull Request
    needs: terraform-docs
    runs-on: ubuntu-22.04
    # if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      # - name: Enable auto-merge
      #   run: gh pr merge --auto --squash "${PR_URL}"
      #   env:
      #     PR_URL: ${{ github.event.pull_request.html_url }}
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve
        run: gh pr review --approve "${PR_URL}"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
