name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    # Skip running release workflow on forks
    if: github.repository_owner == 'craigsloggett'
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Create a GitHub Release
        id: release
        uses: craigsloggett/create-github-release@ca20478970aaddedcef4892d9b6c4109816261c5 # v1.0.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
