name: Security Checks

on: pull_request

permissions:
  contents: read

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli
          output_file_path: console
          quiet: true
          skip_check: CKV_AWS_119,CKV_AWS_28,CKV2_AWS_61,CKV_AWS_144,CKV2_AWS_62,CKV2_AWS_16,CKV_AWS_18,CKV2_AWS_67,CKV2_AWS_28,CKV_TF_1,CKV_TF_2,CKV_AWS_153,CKV_AWS_88,CKV_AWS_91,CKV_AWS_150,CKV_AWS_338,CKV_AWS_293,CKV_AWS_161,CKV_AWS_118,CKV_AWS_191
